Блок с почасовым и 5-дневним прогнозами
Endless1ve/Weather-App pull request #5
Opened 2023-11-21 10:08 UTC by Endless1ve

2023-12-06 14:21 UTC, leka-ren requested changes
В общем все ок, буквально пара моментов, описала их в комментах локально

2023-12-06 14:21 UTC, leka-ren commented on src/blocks/forecasts/forecastContent/dailyContent/dailyContent.css
> +    justify-content: center;
Стоит тогда указать руками дефолтное поведение вне медиа запроса, если есть изменения на каком то из разрешений в параметре

2023-12-06 14:21 UTC, leka-ren commented on src/blocks/forecasts/forecastContent/hourlyContent/hourlyCard/hourlyTime/hourlyTime.css
> +  font-family: "Inter", Arial, Helvetica, sans-serif;
вижу повторения в стиле шрифта, я думала ты вынес, если нет, то вынеси в рут если там те же стили или во что то переиспользуемое

2023-12-06 14:21 UTC, leka-ren commented on src/blocks/forecasts/forecastContent/hourlyContent/hourlyContent.css
> +  display: none;
Понятно) Там больше этих псевдо префексов классов и прочей дребедени которая расширяет отключение в разных вариантах, на разных ОС и браузерах, работа со скроллом одна из бичевских тем фронта, нужно будет разобраться

2023-12-06 14:21 UTC, leka-ren commented on src/blocks/forecasts/forecasts.css
> +  margin-top: 40px;
Скорее заметка чем что то неправильное, если делаешь какие то параметры для отступов или расстановки контента, то стоит явно указывать что ты хочешь видеть и с других сторон. И чисто для подхода "без сюрпризов" стоит указать типа margin: 40px 0 0; типа такого. Не критично, так часто делают, но бывает что такие пасхалки могут вылиться в археологию

2023-12-08 17:25 UTC, Endless1ve commented
Первый пулл для проверки

2023-12-14 15:17 UTC, leka-ren requested changes
Запусти у себя локально это ветку)

2023-12-15 10:36 UTC, Endless1ve commented
> Запусти у себя локально это ветку)

Починил, добавил стили из ветки fix_layout

2023-12-15 17:36 UTC, leka-ren approved these changes
ну с бохом

2023-12-15 17:57 UTC, merged